# Generated by Django 2.2 on 2019-04-19 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('code_category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код категории')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Время редактирования')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Время удаления')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя ребенка')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия ребенка')),
                ('third_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество ребенка')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('age', models.CharField(max_length=100, verbose_name='Возраст')),
                ('address', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Адрес проживания')),
                ('characteristic', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Характеристика на ребенка')),
                ('preferences', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Предпочтения ребенка')),
                ('contacts', models.CharField(blank=True, max_length=200, null=True, verbose_name='Контакты ребенка')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления ребенка')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name': 'Дети',
                'verbose_name_plural': 'Дети',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название программы')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание программы')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон пользователя')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_skill', models.CharField(max_length=5, verbose_name='Код навыка')),
                ('name', models.CharField(max_length=255, verbose_name='Название навыка')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание навыка')),
                ('criterion', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Критерии')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания навыка')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Время редактирование навыка')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Время удаления навыка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill', to='webapp.Categories')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание сессии')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_program', to='webapp.Program', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('done', 'Выполнено'), ('with_hint', 'Выполнено с подсказкой'), ('no_answer', 'Без ответа')], default='no_answer', max_length=255, verbose_name='Статус результата')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_results', to='webapp.Session')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills_results', to='webapp.Skill')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='attending_therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attending_program', to='webapp.UserInfo'),
        ),
        migrations.AddField(
            model_name='program',
            name='author_therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_program', to='webapp.UserInfo'),
        ),
        migrations.AddField(
            model_name='program',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_program', to='webapp.Child', verbose_name='Имя ребенка'),
        ),
        migrations.AddField(
            model_name='program',
            name='skill',
            field=models.ManyToManyField(related_name='skill_program', to='webapp.Skill'),
        ),
        migrations.AddField(
            model_name='child',
            name='first_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fp_child', to='webapp.UserInfo', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='child',
            name='second_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sp_child', to='webapp.UserInfo'),
        ),
    ]
