# Generated by Django 2.2 on 2019-05-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
