# Generated by Django 2.2 on 2019-05-21 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('attending_therapist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attending_test', to='webapp.UserInfo')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_test', to='webapp.Child', verbose_name='Ребенок')),
            ],
        ),
    ]
