# Generated by Django 2.2 on 2019-04-22 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='attending_therapist',
        ),
        migrations.RemoveField(
            model_name='program',
            name='child',
        ),
        migrations.AddField(
            model_name='session',
            name='attending_therapist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='attending_session', to='webapp.UserInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='session_child', to='webapp.Child', verbose_name='Имя ребенка'),
            preserve_default=False,
        ),
    ]
