# Generated by Django 2.2 on 2019-05-06 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_child_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий к программе'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий к навыку'),
        ),
        migrations.AddField(
            model_name='skillsinprogram',
            name='added_skill',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Добавленный навык'),
        ),
        migrations.AddField(
            model_name='skillsinprogram',
            name='added_skill_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий к добавленному навыку'),
        ),
        migrations.AddField(
            model_name='skillsinprogram',
            name='extra_skill_to_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extra_skill_in_program', to='webapp.SkillsInProgram', verbose_name='Поднавык'),
        ),
        migrations.AlterField(
            model_name='result',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_results', to='webapp.Session'),
        ),
        migrations.AlterField(
            model_name='result',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills_results', to='webapp.SkillsInProgram'),
        ),
        migrations.AlterField(
            model_name='session',
            name='attending_therapist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attending_session', to='webapp.UserInfo'),
        ),
    ]
