# Generated by Django 2.2 on 2019-05-22 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0, verbose_name='Уровень владения навыком')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_skill', to='webapp.Skill', verbose_name='Навык')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_result', to='webapp.Test', verbose_name='Тест')),
            ],
        ),
    ]
