# Generated by Django 2.2 on 2019-04-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190422_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='session',
        ),
        migrations.AddField(
            model_name='result',
            name='session',
            field=models.ManyToManyField(related_name='session_results', to='webapp.Session'),
        ),
    ]
