# Generated by Django 2.2 on 2019-05-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество уровней сложности'),
        ),
    ]
